//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextbookManage.Services.Test.SchoolService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchoolService.ISchoolService")]
    public interface ISchoolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetAll", ReplyAction="http://tempuri.org/ISchoolService/GetAllResponse")]
        TextbookManage.Domain.Models.School[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetAll", ReplyAction="http://tempuri.org/ISchoolService/GetAllResponse")]
        System.Threading.Tasks.Task<TextbookManage.Domain.Models.School[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetById", ReplyAction="http://tempuri.org/ISchoolService/GetByIdResponse")]
        TextbookManage.Domain.Models.School GetById(string schoolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetById", ReplyAction="http://tempuri.org/ISchoolService/GetByIdResponse")]
        System.Threading.Tasks.Task<TextbookManage.Domain.Models.School> GetByIdAsync(string schoolId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchoolServiceChannel : TextbookManage.Services.Test.SchoolService.ISchoolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchoolServiceClient : System.ServiceModel.ClientBase<TextbookManage.Services.Test.SchoolService.ISchoolService>, TextbookManage.Services.Test.SchoolService.ISchoolService {
        
        public SchoolServiceClient() {
        }
        
        public SchoolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchoolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TextbookManage.Domain.Models.School[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<TextbookManage.Domain.Models.School[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public TextbookManage.Domain.Models.School GetById(string schoolId) {
            return base.Channel.GetById(schoolId);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.Domain.Models.School> GetByIdAsync(string schoolId) {
            return base.Channel.GetByIdAsync(schoolId);
        }
    }
}
