//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18046
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextbookManage.WebUI.DeclarationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchoolView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    public partial class SchoolView : TextbookManage.WebUI.DeclarationService.BaseViewModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolId {
            get {
                return this.SchoolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolIdField, value) != true)) {
                    this.SchoolIdField = value;
                    this.RaisePropertyChanged("SchoolId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseViewModel", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.DepartmentView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.CourseView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.TeachingTaskView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.TextbookForDeclarationView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.DeclarationView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.ResponseView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.ProfessionalClassBaseView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.ProfessionalClassView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.DeclarationBaseView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.DeclarationForTeachingTaskView))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.SchoolView))]
    public partial class BaseViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeleteFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeleteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckFlag {
            get {
                return this.CheckFlagField;
            }
            set {
                if ((this.CheckFlagField.Equals(value) != true)) {
                    this.CheckFlagField = value;
                    this.RaisePropertyChanged("CheckFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeleteFlag {
            get {
                return this.DeleteFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.DeleteFlagField, value) != true)) {
                    this.DeleteFlagField = value;
                    this.RaisePropertyChanged("DeleteFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDelete {
            get {
                return this.IsDeleteField;
            }
            set {
                if ((this.IsDeleteField.Equals(value) != true)) {
                    this.IsDeleteField = value;
                    this.RaisePropertyChanged("IsDelete");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    public partial class DepartmentView : TextbookManage.WebUI.DeclarationService.BaseViewModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIdField, value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    public partial class CourseView : TextbookManage.WebUI.DeclarationService.BaseViewModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumAndNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseIdField, value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num {
            get {
                return this.NumField;
            }
            set {
                if ((object.ReferenceEquals(this.NumField, value) != true)) {
                    this.NumField = value;
                    this.RaisePropertyChanged("Num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumAndName {
            get {
                return this.NumAndNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NumAndNameField, value) != true)) {
                    this.NumAndNameField = value;
                    this.RaisePropertyChanged("NumAndName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeachingTaskView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    public partial class TeachingTaskView : TextbookManage.WebUI.DeclarationService.BaseViewModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSignNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclarationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeachingTaskNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSignName {
            get {
                return this.DataSignNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSignNameField, value) != true)) {
                    this.DataSignNameField = value;
                    this.RaisePropertyChanged("DataSignName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclarationState {
            get {
                return this.DeclarationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclarationStateField, value) != true)) {
                    this.DeclarationStateField = value;
                    this.RaisePropertyChanged("DeclarationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentCount {
            get {
                return this.StudentCountField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentCountField, value) != true)) {
                    this.StudentCountField = value;
                    this.RaisePropertyChanged("StudentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherName {
            get {
                return this.TeacherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherNameField, value) != true)) {
                    this.TeacherNameField = value;
                    this.RaisePropertyChanged("TeacherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeachingTaskNum {
            get {
                return this.TeachingTaskNumField;
            }
            set {
                if ((object.ReferenceEquals(this.TeachingTaskNumField, value) != true)) {
                    this.TeachingTaskNumField = value;
                    this.RaisePropertyChanged("TeachingTaskNum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextbookForDeclarationView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    public partial class TextbookForDeclarationView : TextbookManage.WebUI.DeclarationService.BaseViewModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextbookIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((object.ReferenceEquals(this.IsbnField, value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num {
            get {
                return this.NumField;
            }
            set {
                if ((object.ReferenceEquals(this.NumField, value) != true)) {
                    this.NumField = value;
                    this.RaisePropertyChanged("Num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextbookId {
            get {
                return this.TextbookIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TextbookIdField, value) != true)) {
                    this.TextbookIdField = value;
                    this.RaisePropertyChanged("TextbookId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeclarationView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    public partial class DeclarationView : TextbookManage.WebUI.DeclarationService.BaseViewModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclarantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclarationCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclarationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NotNeedTextbookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TeachingTaskNumsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextbookIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Declarant {
            get {
                return this.DeclarantField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclarantField, value) != true)) {
                    this.DeclarantField = value;
                    this.RaisePropertyChanged("Declarant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclarationCount {
            get {
                return this.DeclarationCountField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclarationCountField, value) != true)) {
                    this.DeclarationCountField = value;
                    this.RaisePropertyChanged("DeclarationCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclarationId {
            get {
                return this.DeclarationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclarationIdField, value) != true)) {
                    this.DeclarationIdField = value;
                    this.RaisePropertyChanged("DeclarationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotNeedTextbook {
            get {
                return this.NotNeedTextbookField;
            }
            set {
                if ((this.NotNeedTextbookField.Equals(value) != true)) {
                    this.NotNeedTextbookField = value;
                    this.RaisePropertyChanged("NotNeedTextbook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] TeachingTaskNums {
            get {
                return this.TeachingTaskNumsField;
            }
            set {
                if ((object.ReferenceEquals(this.TeachingTaskNumsField, value) != true)) {
                    this.TeachingTaskNumsField = value;
                    this.RaisePropertyChanged("TeachingTaskNums");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextbookId {
            get {
                return this.TextbookIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TextbookIdField, value) != true)) {
                    this.TextbookIdField = value;
                    this.RaisePropertyChanged("TextbookId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    public partial class ResponseView : TextbookManage.WebUI.DeclarationService.BaseViewModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfessionalClassBaseView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.ProfessionalClassView))]
    public partial class ProfessionalClassBaseView : TextbookManage.WebUI.DeclarationService.BaseViewModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionalClassIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfessionalClassId {
            get {
                return this.ProfessionalClassIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionalClassIdField, value) != true)) {
                    this.ProfessionalClassIdField = value;
                    this.RaisePropertyChanged("ProfessionalClassId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfessionalClassView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    public partial class ProfessionalClassView : TextbookManage.WebUI.DeclarationService.ProfessionalClassBaseView {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num {
            get {
                return this.NumField;
            }
            set {
                if ((object.ReferenceEquals(this.NumField, value) != true)) {
                    this.NumField = value;
                    this.RaisePropertyChanged("Num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentCount {
            get {
                return this.StudentCountField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentCountField, value) != true)) {
                    this.StudentCountField = value;
                    this.RaisePropertyChanged("StudentCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeclarationBaseView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TextbookManage.WebUI.DeclarationService.DeclarationForTeachingTaskView))]
    public partial class DeclarationBaseView : TextbookManage.WebUI.DeclarationService.BaseViewModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclarantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclarationCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclarationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclarationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionalClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeachingTaskNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextbookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextbookNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextbookNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Declarant {
            get {
                return this.DeclarantField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclarantField, value) != true)) {
                    this.DeclarantField = value;
                    this.RaisePropertyChanged("Declarant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclarationCount {
            get {
                return this.DeclarationCountField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclarationCountField, value) != true)) {
                    this.DeclarationCountField = value;
                    this.RaisePropertyChanged("DeclarationCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclarationDate {
            get {
                return this.DeclarationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclarationDateField, value) != true)) {
                    this.DeclarationDateField = value;
                    this.RaisePropertyChanged("DeclarationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclarationId {
            get {
                return this.DeclarationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclarationIdField, value) != true)) {
                    this.DeclarationIdField = value;
                    this.RaisePropertyChanged("DeclarationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfessionalClassName {
            get {
                return this.ProfessionalClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionalClassNameField, value) != true)) {
                    this.ProfessionalClassNameField = value;
                    this.RaisePropertyChanged("ProfessionalClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeachingTaskNum {
            get {
                return this.TeachingTaskNumField;
            }
            set {
                if ((object.ReferenceEquals(this.TeachingTaskNumField, value) != true)) {
                    this.TeachingTaskNumField = value;
                    this.RaisePropertyChanged("TeachingTaskNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextbookId {
            get {
                return this.TextbookIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TextbookIdField, value) != true)) {
                    this.TextbookIdField = value;
                    this.RaisePropertyChanged("TextbookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextbookName {
            get {
                return this.TextbookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TextbookNameField, value) != true)) {
                    this.TextbookNameField = value;
                    this.RaisePropertyChanged("TextbookName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextbookNum {
            get {
                return this.TextbookNumField;
            }
            set {
                if ((object.ReferenceEquals(this.TextbookNumField, value) != true)) {
                    this.TextbookNumField = value;
                    this.RaisePropertyChanged("TextbookNum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeclarationForTeachingTaskView", Namespace="http://schemas.datacontract.org/2004/07/TextbookManage.ViewModels")]
    [System.SerializableAttribute()]
    public partial class DeclarationForTeachingTaskView : TextbookManage.WebUI.DeclarationService.DeclarationBaseView {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Edition {
            get {
                return this.EditionField;
            }
            set {
                if ((object.ReferenceEquals(this.EditionField, value) != true)) {
                    this.EditionField = value;
                    this.RaisePropertyChanged("Edition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((object.ReferenceEquals(this.IsbnField, value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Press {
            get {
                return this.PressField;
            }
            set {
                if ((object.ReferenceEquals(this.PressField, value) != true)) {
                    this.PressField = value;
                    this.RaisePropertyChanged("Press");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintCount {
            get {
                return this.PrintCountField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintCountField, value) != true)) {
                    this.PrintCountField = value;
                    this.RaisePropertyChanged("PrintCount");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeclarationService.IDeclarationAppl")]
    public interface IDeclarationAppl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetSchoolByLoginName", ReplyAction="http://tempuri.org/IDeclarationAppl/GetSchoolByLoginNameResponse")]
        TextbookManage.WebUI.DeclarationService.SchoolView[] GetSchoolByLoginName(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetSchoolByLoginName", ReplyAction="http://tempuri.org/IDeclarationAppl/GetSchoolByLoginNameResponse")]
        System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.SchoolView[]> GetSchoolByLoginNameAsync(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetDepartmentByLoginName", ReplyAction="http://tempuri.org/IDeclarationAppl/GetDepartmentByLoginNameResponse")]
        TextbookManage.WebUI.DeclarationService.DepartmentView[] GetDepartmentByLoginName(string loginName, string schoolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetDepartmentByLoginName", ReplyAction="http://tempuri.org/IDeclarationAppl/GetDepartmentByLoginNameResponse")]
        System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.DepartmentView[]> GetDepartmentByLoginNameAsync(string loginName, string schoolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetCourseByDepartmentId", ReplyAction="http://tempuri.org/IDeclarationAppl/GetCourseByDepartmentIdResponse")]
        TextbookManage.WebUI.DeclarationService.CourseView[] GetCourseByDepartmentId(string departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetCourseByDepartmentId", ReplyAction="http://tempuri.org/IDeclarationAppl/GetCourseByDepartmentIdResponse")]
        System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.CourseView[]> GetCourseByDepartmentIdAsync(string departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetTeachingTaskByDepartmentId", ReplyAction="http://tempuri.org/IDeclarationAppl/GetTeachingTaskByDepartmentIdResponse")]
        TextbookManage.WebUI.DeclarationService.TeachingTaskView[] GetTeachingTaskByDepartmentId(string departmentId, string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetTeachingTaskByDepartmentId", ReplyAction="http://tempuri.org/IDeclarationAppl/GetTeachingTaskByDepartmentIdResponse")]
        System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.TeachingTaskView[]> GetTeachingTaskByDepartmentIdAsync(string departmentId, string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetTextbooksByName", ReplyAction="http://tempuri.org/IDeclarationAppl/GetTextbooksByNameResponse")]
        TextbookManage.WebUI.DeclarationService.TextbookForDeclarationView[] GetTextbooksByName(string name, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetTextbooksByName", ReplyAction="http://tempuri.org/IDeclarationAppl/GetTextbooksByNameResponse")]
        System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.TextbookForDeclarationView[]> GetTextbooksByNameAsync(string name, string isbn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/SubmitStudentDeclaration", ReplyAction="http://tempuri.org/IDeclarationAppl/SubmitStudentDeclarationResponse")]
        TextbookManage.WebUI.DeclarationService.ResponseView SubmitStudentDeclaration(TextbookManage.WebUI.DeclarationService.DeclarationView view);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/SubmitStudentDeclaration", ReplyAction="http://tempuri.org/IDeclarationAppl/SubmitStudentDeclarationResponse")]
        System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.ResponseView> SubmitStudentDeclarationAsync(TextbookManage.WebUI.DeclarationService.DeclarationView view);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/SubmitTeacherDeclaration", ReplyAction="http://tempuri.org/IDeclarationAppl/SubmitTeacherDeclarationResponse")]
        TextbookManage.WebUI.DeclarationService.ResponseView SubmitTeacherDeclaration(TextbookManage.WebUI.DeclarationService.DeclarationView view);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/SubmitTeacherDeclaration", ReplyAction="http://tempuri.org/IDeclarationAppl/SubmitTeacherDeclarationResponse")]
        System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.ResponseView> SubmitTeacherDeclarationAsync(TextbookManage.WebUI.DeclarationService.DeclarationView view);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetProfessionalClassByTeachingTaskNum", ReplyAction="http://tempuri.org/IDeclarationAppl/GetProfessionalClassByTeachingTaskNumResponse" +
            "")]
        TextbookManage.WebUI.DeclarationService.ProfessionalClassView[] GetProfessionalClassByTeachingTaskNum(string teachingTaskNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetProfessionalClassByTeachingTaskNum", ReplyAction="http://tempuri.org/IDeclarationAppl/GetProfessionalClassByTeachingTaskNumResponse" +
            "")]
        System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.ProfessionalClassView[]> GetProfessionalClassByTeachingTaskNumAsync(string teachingTaskNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetDeclarationByTeacingTaskNum", ReplyAction="http://tempuri.org/IDeclarationAppl/GetDeclarationByTeacingTaskNumResponse")]
        TextbookManage.WebUI.DeclarationService.DeclarationForTeachingTaskView[] GetDeclarationByTeacingTaskNum(string teachingTaskNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/GetDeclarationByTeacingTaskNum", ReplyAction="http://tempuri.org/IDeclarationAppl/GetDeclarationByTeacingTaskNumResponse")]
        System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.DeclarationForTeachingTaskView[]> GetDeclarationByTeacingTaskNumAsync(string teachingTaskNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/CalculateDeclarationCount", ReplyAction="http://tempuri.org/IDeclarationAppl/CalculateDeclarationCountResponse")]
        string CalculateDeclarationCount(TextbookManage.WebUI.DeclarationService.TeachingTaskView[] views);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeclarationAppl/CalculateDeclarationCount", ReplyAction="http://tempuri.org/IDeclarationAppl/CalculateDeclarationCountResponse")]
        System.Threading.Tasks.Task<string> CalculateDeclarationCountAsync(TextbookManage.WebUI.DeclarationService.TeachingTaskView[] views);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeclarationApplChannel : TextbookManage.WebUI.DeclarationService.IDeclarationAppl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeclarationApplClient : System.ServiceModel.ClientBase<TextbookManage.WebUI.DeclarationService.IDeclarationAppl>, TextbookManage.WebUI.DeclarationService.IDeclarationAppl {
        
        public DeclarationApplClient() {
        }
        
        public DeclarationApplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeclarationApplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeclarationApplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeclarationApplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TextbookManage.WebUI.DeclarationService.SchoolView[] GetSchoolByLoginName(string loginName) {
            return base.Channel.GetSchoolByLoginName(loginName);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.SchoolView[]> GetSchoolByLoginNameAsync(string loginName) {
            return base.Channel.GetSchoolByLoginNameAsync(loginName);
        }
        
        public TextbookManage.WebUI.DeclarationService.DepartmentView[] GetDepartmentByLoginName(string loginName, string schoolId) {
            return base.Channel.GetDepartmentByLoginName(loginName, schoolId);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.DepartmentView[]> GetDepartmentByLoginNameAsync(string loginName, string schoolId) {
            return base.Channel.GetDepartmentByLoginNameAsync(loginName, schoolId);
        }
        
        public TextbookManage.WebUI.DeclarationService.CourseView[] GetCourseByDepartmentId(string departmentId) {
            return base.Channel.GetCourseByDepartmentId(departmentId);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.CourseView[]> GetCourseByDepartmentIdAsync(string departmentId) {
            return base.Channel.GetCourseByDepartmentIdAsync(departmentId);
        }
        
        public TextbookManage.WebUI.DeclarationService.TeachingTaskView[] GetTeachingTaskByDepartmentId(string departmentId, string courseId) {
            return base.Channel.GetTeachingTaskByDepartmentId(departmentId, courseId);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.TeachingTaskView[]> GetTeachingTaskByDepartmentIdAsync(string departmentId, string courseId) {
            return base.Channel.GetTeachingTaskByDepartmentIdAsync(departmentId, courseId);
        }
        
        public TextbookManage.WebUI.DeclarationService.TextbookForDeclarationView[] GetTextbooksByName(string name, string isbn) {
            return base.Channel.GetTextbooksByName(name, isbn);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.TextbookForDeclarationView[]> GetTextbooksByNameAsync(string name, string isbn) {
            return base.Channel.GetTextbooksByNameAsync(name, isbn);
        }
        
        public TextbookManage.WebUI.DeclarationService.ResponseView SubmitStudentDeclaration(TextbookManage.WebUI.DeclarationService.DeclarationView view) {
            return base.Channel.SubmitStudentDeclaration(view);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.ResponseView> SubmitStudentDeclarationAsync(TextbookManage.WebUI.DeclarationService.DeclarationView view) {
            return base.Channel.SubmitStudentDeclarationAsync(view);
        }
        
        public TextbookManage.WebUI.DeclarationService.ResponseView SubmitTeacherDeclaration(TextbookManage.WebUI.DeclarationService.DeclarationView view) {
            return base.Channel.SubmitTeacherDeclaration(view);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.ResponseView> SubmitTeacherDeclarationAsync(TextbookManage.WebUI.DeclarationService.DeclarationView view) {
            return base.Channel.SubmitTeacherDeclarationAsync(view);
        }
        
        public TextbookManage.WebUI.DeclarationService.ProfessionalClassView[] GetProfessionalClassByTeachingTaskNum(string teachingTaskNum) {
            return base.Channel.GetProfessionalClassByTeachingTaskNum(teachingTaskNum);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.ProfessionalClassView[]> GetProfessionalClassByTeachingTaskNumAsync(string teachingTaskNum) {
            return base.Channel.GetProfessionalClassByTeachingTaskNumAsync(teachingTaskNum);
        }
        
        public TextbookManage.WebUI.DeclarationService.DeclarationForTeachingTaskView[] GetDeclarationByTeacingTaskNum(string teachingTaskNum) {
            return base.Channel.GetDeclarationByTeacingTaskNum(teachingTaskNum);
        }
        
        public System.Threading.Tasks.Task<TextbookManage.WebUI.DeclarationService.DeclarationForTeachingTaskView[]> GetDeclarationByTeacingTaskNumAsync(string teachingTaskNum) {
            return base.Channel.GetDeclarationByTeacingTaskNumAsync(teachingTaskNum);
        }
        
        public string CalculateDeclarationCount(TextbookManage.WebUI.DeclarationService.TeachingTaskView[] views) {
            return base.Channel.CalculateDeclarationCount(views);
        }
        
        public System.Threading.Tasks.Task<string> CalculateDeclarationCountAsync(TextbookManage.WebUI.DeclarationService.TeachingTaskView[] views) {
            return base.Channel.CalculateDeclarationCountAsync(views);
        }
    }
}
