//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextbookManage.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declaration
    {
        public Declaration()
        {
            this.Subscription = new HashSet<Subscription>();
            this.DeclarationApproval = new HashSet<DeclarationApproval>();
        }
    
        public int ID { get; set; }
        public DeclarationType Type { get; set; }
    
        public virtual TeachingTask TeachingTask { get; set; }
        public virtual Textbook Textbook { get; set; }
        public virtual ICollection<Subscription> Subscription { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<DeclarationApproval> DeclarationApproval { get; set; }
    }
}
