//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextbookManage.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.Declaration = new HashSet<Declaration>();
        }
    
        public int ID { get; set; }
    
        public virtual ICollection<Declaration> Declaration { get; set; }
        public virtual BookSeller BookSeller { get; set; }
        public virtual Term Term { get; set; }
        public virtual Feedback Feedback { get; set; }
        public virtual Textbook Textbook { get; set; }
    }
}
