//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextbookManage.Design
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TextbookManageV3Container : DbContext
    {
        public TextbookManageV3Container()
            : base("name=TextbookManageV3Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<TeachingTask> TeachingTasks { get; set; }
        public DbSet<Term> Terms { get; set; }
        public DbSet<DataSign> DataSigns { get; set; }
        public DbSet<Declaration> Declarations { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<Textbook> Textbooks { get; set; }
        public DbSet<Discount> Discounts { get; set; }
        public DbSet<Approval> Approvals { get; set; }
        public DbSet<BookSeller> BookSellers { get; set; }
        public DbSet<Storage> Storages { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<StockRecord> StockRecords { get; set; }
        public DbSet<ReleaseRecord> ReleaseRecords { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<Student> Student集 { get; set; }
        public DbSet<School> School集 { get; set; }
        public DbSet<Department> Department集 { get; set; }
    }
}
